### ISSUE TITLE
Dark Mode Issue - Clean Theme

### ISSUE THREAD

**Issue by mansoorih** [felixhahnweilheim/humhub-dark-mode#57]
Hi Felix,

I few months back, I had reported dark mode issue when an update to Clean theme had been rolled out. There was an update provided back then and it resolved. However, with the most latest updated to the Clean Theme once again the issue has resurfaced. I have Clean Theme and Dark Mode Module installed. It's almost impossible to read. Please see screenshot.

![image](https://github.com/user-attachments/assets/307bea29-453f-430d-a6ae-b8b7b98d689c)

**Comment by mansoorih** [comment]
![image](https://github.com/user-attachments/assets/78c9da13-242f-47d6-a53e-5e5a7ea0db92)
One more screenshot

**Comment by marc-farre** [comment]
@mansoorih Thanks for reporting this issue.

I'm aware of it, but I'm missing time to support the dark mode for this Clean Theme module.

It's because of the new Clean Theme module configuration, which allows choosing the theme colors.

Maybe we should add colors for dark mode, like it was done for the Flex theme: https://github.com/felixhahnweilheim/humhub-flex-theme

Or automatically generate dark colors from the selected light colors.

Since it's a free module, feel free to participate in the code, or pay a developer for it, or make a donation that could help us work on it.

**Comment by mansoorih** [comment]
Thanks for sharing the update. Sadly, I'm not a developer, so would be unable to contribute to the code. Being a free website with just 135+ members, I have collected just $50 donations this year. So unfortunately, I can't pay a developer or donate for theme development. I still have to collect some more funds to renew modules that expired last month.

**Comment by mansoorih** [comment]
The last application code I wrote was back in 1997. There was no PHP back then. I wish I could have had a chance to continue coding.

**Comment by marc-farre** [comment]
@mansoorih thanks, I understand of course.

I personally prefer spending time on working to integrate the Bootstrap 5.3 native dark mode: https://github.com/felixhahnweilheim/humhub-dark-mode/issues/56#issuecomment-2249579664

**Comment by mansoorih** [comment]
Appreciate for sharing the active conversation update on this topic, @marc-farre.

**Comment by felixhahnweilheim** [comment]
Just for your information, using HumHub (dark) in the Dark Mode module settings looks a bit better than clean-theme (dark). But this is only a temporary thing.

I will see if I can create a PR to fix the issue next week.
Making the dark mode colors also configurable would be the best option but probably too much effort (for a free module).

**Comment by mansoorih** [comment]
Yes, HumHub default theme in dark mode works. However, I personally liked the Clean Theme, since it gives a wider screen canvas and spacing compared to the default HumHub theme which I think shrinks the width to 1024 pixels.

**Comment by felixhahnweilheim** [comment]
fixed in https://github.com/cuzy-app/clean-theme/pull/24

**Comment by marc-farre** [comment]
@felixhahnweilheim Thank you very much, great job!
I've released version 2.0.3: https://github.com/cuzy-app/clean-theme/releases/tag/2.0.3

I have removed CSS about the `#topbar-first` and `#topbar-second` as they don't exist on the Clean theme and added CSS for the bottom bar because it wasn't contrasted enough:
https://github.com/cuzy-app/clean-theme/blob/master/themes/Clean/css/dark.css#L77-L90

I also removed the dark CSS non minimized because the gain was only 2 Kb and since there is no automatic minifier in the compiler script, I though we might forget to compile it. Moreover, each time I save the file with phpStorm it refactors the file (unminimizes)...

**Comment by mansoorih** [comment]
Gents, thanks, I upgraded Clean Theme, but looks like something still missing.. just for me to double-check, I had the Clean Theme under Appearance selected, and Clean Dark under the Dark Mode module selected.
![image](https://github.com/user-attachments/assets/497a938b-8dd4-44c3-9b94-5a718c1a76d3)

**Comment by marc-farre** [comment]
@mansoorih thanks for sharing.
I've also seen small issues here:
![image](https://github.com/user-attachments/assets/921b96c2-af0e-4faf-a4bd-e83166e90513)

Maybe we should list them all, and when someone has time to fix them, I'll release a new version of the module.

**Comment by mansoorih** [comment]
![image](https://github.com/user-attachments/assets/9e8b0020-97e2-4307-8d01-e4261a1f5870)
![image](https://github.com/user-attachments/assets/99acb329-a0a1-4b36-93ac-cbbd92d78e4b)
![image](https://github.com/user-attachments/assets/0a412804-03e9-4f6a-844d-475f0813854c)

Few more screenshots to add to the list.

**Comment by marc-farre** [comment]
@mansoorih @felixhahnweilheim I've released version 2.0.4 which fixes dark colors

**Comment by mansoorih** [comment]
Thanks, just updated and will check all places. Just did a quick check with Reactions module that I purchased a few days back. There seems to be issue, not sure if it is with the Reactions module or Dark theme or Clean theme, but hard to read text. Screenshot pasted. 
![image](https://github.com/user-attachments/assets/03ea5128-35fd-4233-8c19-3e8306a51b75)

**Comment by marc-farre** [comment]
@mansoorih Thanks for reporting this issue with the Reaction module.
Just released version 1.2.3 which now uses CSS variables too.

**Comment by mansoorih** [comment]
Thanks, @marc-farre and @felixhahnweilheim for all your attention and support.

**Comment by mansoorih** [comment]
Strangely, I noticed this issue in the message module.

![image](https://github.com/user-attachments/assets/f105a8b5-951a-4718-961a-ea4f4a0f6c46)

**Comment by marc-farre** [comment]
@mansoorih Fixed by @felixhahnweilheim in PR https://github.com/cuzy-app/clean-theme/pull/25
Will be available in next release.

**Comment by mansoorih** [comment]
Something still is broken in dark mode. Can't read filename when attached.
![image](https://github.com/user-attachments/assets/eda429a0-bfc5-4f2b-b08d-b9fc579322a7)

**Comment by felixhahnweilheim** [comment]
I can not reproduce this in HH 1.16
Which versions (HumHub, Dark Mode, Clean Theme) do you have?

**Comment by mansoorih** [comment]
HumHub Community Edition Version: 1.16.2
Clean Theme Version 2.0.6
Dark Mode Version 1.0.8

**Comment by felixhahnweilheim** [comment]
Please update Clean Theme to v2.1
I think the issue is solved, if not let me know.

**Comment by mansoorih** [comment]
Surprisingly, after I upgraded HumHub to 1.16.2 when it was released, I have seen no updates for any of the modules visible to me, including the Clean Theme.

**Comment by marc-farre** [comment]
@mansoorih Clean Theme version 2.1 is for HumHub 1.17 which is still in beta (but already quite stable).
